/**
 * Created by phanmduong on 4/5/17.
 */
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const CHANGE_STATUSBAR_COLOR = 'CHANGE_STATUSBAR_COLOR';

export const UPDATE_DATA_LOGIN_FORM = 'UPDATE_DATA_LOGIN_FORM';
export const BEGIN_LOGIN = 'BEGIN_LOGIN';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const GOT_DATA_LOGIN = 'GOT_DATA_LOGIN';
export const SET_AUTO_LOGIN = 'SET_AUTO_LOGIN';

export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const DISABLE_DRAWER = 'DISABLE_DRAWER';
export const ENABLE_DRAWER = 'ENABLE_DRAWER';

export const BEGIN_DATA_BASE_LOAD = 'BEGIN_DATA_BASE_LOAD';
export const LOAD_DATA_BASE_SUCCESSFUL = 'LOAD_DATA_BASE_SUCCESSFUL';
export const LOAD_DATA_BASE_ERROR = 'LOAD_DATA_BASE_ERROR';
export const SELECTED_BASE_ID = 'SELECTED_BASE_ID';

export const BEGIN_DATA_COURSE_LOAD = 'BEGIN_DATA_COURSE_LOAD';
export const LOAD_DATA_COURSE_SUCCESSFUL = 'LOAD_DATA_COURSE_SUCCESSFUL';
export const LOAD_DATA_COURSE_ERROR = 'LOAD_DATA_COURSE_ERROR';
export const SELECTED_COURSE_ID = 'SELECTED_COURSE_ID';

export const BEGIN_DATA_GEN_LOAD = 'BEGIN_DATA_GEN_LOAD';
export const LOAD_DATA_GEN_SUCCESSFUL = 'LOAD_DATA_GEN_SUCCESSFUL';
export const LOAD_DATA_GEN_ERROR = 'LOAD_DATA_GEN_ERROR';
export const SELECTED_GEN_ID = 'SELECTED_GEN_ID';

export const BEGIN_DATA_LESSON_COURSE_LOAD = 'BEGIN_DATA_LESSON_COURSE_LOAD';
export const LOAD_DATA_LESSON_COURSE_SUCCESSFUL =
  'LOAD_DATA_LESSON_COURSE_SUCCESSFUL';
export const LOAD_DATA_LESSON_COURSE_ERROR = 'LOAD_DATA_LESSON_COURSE_ERROR';
export const SELECTED_LESSON_COURSE_ID = 'SELECTED_LESSON_COURSE_ID';

export const BEGIN_DATA_CLASS_LOAD = 'BEGIN_DATA_CLASS_LOAD';
export const LOAD_DATA_CLASS_SUCCESSFUL = 'LOAD_DATA_CLASS_SUCCESSFUL';
export const LOAD_DATA_CLASS_ERROR = 'LOAD_DATA_CLASS_ERROR';
export const BEGIN_DATA_COURSES_LOAD = 'BEGIN_DATA_COURSES_LOAD';
export const LOAD_DATA_COURSES_SUCCESSFUL = 'LOAD_DATA_COURSES_SUCCESSFUL';
export const LOAD_DATA_COURSES_ERROR = 'LOAD_DATA_COURSES_ERROR';
export const SELECTED_CLASS_ID = 'SELECTED_CLASS_ID';

export const BEGIN_DATA_CURRENT_CLASS_STUDY_LOAD =
  'BEGIN_DATA_CURRENT_CLASS_STUDY_LOAD';
export const LOAD_DATA_CURRENT_CLASS_STUDY_SUCCESSFUL =
  'LOAD_DATA_CURRENT_CLASS_STUDY_SUCCESSFUL';
export const LOAD_DATA_CURRENT_CLASS_STUDY_ERROR =
  'LOAD_DATA_CURRENT_CLASS_STUDY_ERROR';
export const SELECTED_CURRENT_CLASS_STUDY = 'SELECTED_CURRENT_CLASS_STUDY';

export const BEGIN_SCAN_QR_CODE = 'BEGIN_SCAN_QR_CODE';
export const SCANNED_QR_CODE = 'SCANNED_QR_CODE';
export const IS_SCANNED_QR_CODE = 'IS_SCANNED_QR_CODE';

export const BEGIN_GET_INFOR_STUDENT = 'BEGIN_GET_INFOR_STUDENT';
export const LOAD_GET_INFOR_STUDENT_SUCCESSFUL =
  'LOAD_GET_INFOR_STUDENT_SUCCESSFUL';
export const LOAD_GET_INFOR_STUDENT_ERROR = 'LOAD_GET_INFOR_STUDENT_ERROR';
export const BEGIN_POST_ATTENDANCE_STUDENT = 'BEGIN_POST_ATTENDANCE_STUDENT';
export const LOAD_POST_ATTENDANCE_STUDENT_SUCCESSFUL =
  'LOAD_POST_ATTENDANCE_STUDENT_SUCCESSFUL';
export const LOAD_POST_ATTENDANCE_STUDENT_ERROR =
  'LOAD_POST_ATTENDANCE_STUDENT_ERROR';
export const BEGIN_UNBLOCK_STUDENT = 'BEGIN_UNBLOCK_STUDENT';
export const LOAD_UNBLOCKING_STUDENT = 'LOAD_UNBLOCKING_STUDENT';
export const ERROR_UNBLOCKING_STUDENT = 'ERROR_UNBLOCKING_STUDENT';
export const BEGIN_UPLOAD_IMAGE_STUDENT = 'BEGIN_UPLOAD_IMAGE_STUDENT';
export const UPLOAD_IMAGE_STUDENT = 'UPLOAD_IMAGE_STUDENT';

export const HISTORY_TEACHING_TAB = 'HISTORY_TEACHING_TAB';
export const HISTORY_WORK_SHIFT_TAB = 'HISTORY_WORK_SHIFT_TAB';
export const HISTORY_SHIFT_TAB = 'HISTORY_SHIFT_TAB';

export const BEGIN_DATA_SHIFT_REGISTER_LOAD = 'BEGIN_DATA_SHIFT_REGISTER_LOAD';
export const LOAD_DATA_SHIFT_REGISTER_SUCCESSFUL =
  'LOAD_DATA_SHIFT_REGISTER_SUCCESSFUL';
export const LOAD_DATA_SHIFT_REGISTER_ERROR = 'LOAD_DATA_SHIFT_REGISTER_ERROR';
export const POST_SHIFT_REGISTER = 'POST_SHIFT_REGISTER';
export const SHIFT_REGISTER_SUCCESSFUL = 'SHIFT_REGISTER_SUCCESSFUL';
export const SHIFT_REGISTER_ERROR = 'SHIFT_REGISTER_ERROR';
export const POST_SHIFT_UNREGISTER = 'POST_SHIFT_UNREGISTER';
export const SHIFT_UNREGISTER_SUCCESSFUL = 'SHIFT_UNREGISTER_SUCCESSFUL';
export const SHIFT_UNREGISTER_ERROR = 'SHIFT_UNREGISTER_ERROR';
export const SELECTED_BASE_ID_SHIFT_REGISTER =
  'SELECTED_BASE_ID_SHIFT_REGISTER';
export const SELECTED_GEN_ID_SHIFT_REGISTER = 'SELECTED_GEN_ID_SHIFT_REGISTER';
export const UPDATE_DATA_SHIFT_REGISTER = 'UPDATE_DATA_SHIFT_REGISTER';

export const BEGIN_DATA_ANALYTICS_LOAD = 'BEGIN_DATA_ANALYTICS_LOAD';
export const LOAD_DATA_ANALYTICS_SUCCESSFUL = 'LOAD_DATA_ANALYTICS_SUCCESSFUL';
export const LOAD_DATA_ANALYTICS_ERROR = 'LOAD_DATA_ANALYTICS_ERROR';
export const SELECTED_BASE_ID_ANALYTICS = 'SELECTED_BASE_ID_ANALYTICS';
export const SELECTED_GEN_ID_ANALYTICS = 'SELECTED_GEN_ID_ANALYTICS';

export const BEGIN_DATA_LIST_STUDENT_CLASS_LOAD =
  'BEGIN_DATA_LIST_STUDENT_CLASS_LOAD';
export const LOAD_DATA_LIST_STUDENT_CLASS_SUCCESSFUL =
  'LOAD_DATA_LIST_STUDENT_CLASS_SUCCESSFUL';
export const LOAD_DATA_LIST_STUDENT_CLASS_ERROR =
  'LOAD_DATA_LIST_STUDENT_CLASS_ERROR';

export const BEGIN_DATA_REGISTER_LIST_LOAD_ALL =
  'BEGIN_DATA_REGISTER_LIST_LOAD_ALL';
export const LOAD_DATA_REGISTER_LIST_SUCCESSFUL_ALL =
  'LOAD_DATA_REGISTER_LIST_SUCCESSFUL_ALL';
export const LOAD_DATA_REGISTER_LIST_ERROR_ALL =
  'LOAD_DATA_REGISTER_LIST_ERROR_ALL';
export const UPDATE_FORM_SEARCH_REGISTER_LIST_ALL =
  'UPDATE_FORM_SEARCH_REGISTER_LIST_ALL';
export const BEGIN_DATA_REGISTER_LIST_LOAD_MY =
  'BEGIN_DATA_REGISTER_LIST_LOAD_MY';
export const LOAD_DATA_REGISTER_LIST_SUCCESSFUL_MY =
  'LOAD_DATA_REGISTER_LIST_SUCCESSFUL_MY';
export const LOAD_DATA_REGISTER_LIST_ERROR_MY =
  'LOAD_DATA_REGISTER_LIST_ERROR_MY';
export const UPDATE_FORM_SEARCH_REGISTER_LIST_MY =
  'UPDATE_FORM_SEARCH_REGISTER_LIST_MY';
export const CHANGE_SEGMENT_REGISTER_LIST = 'CHANGE_SEGMENT_REGISTER_LIST';

export const BEGIN_DATA_STUDENT_LIST_COLLECT_MONEY_LOAD =
  'BEGIN_DATA_STUDENT_LIST_COLLECT_MONEY_LOAD';
export const LOAD_DATA_STUDENT_LIST_COLLECT_MONEY_SUCCESSFUL =
  'LOAD_DATA_STUDENT_LIST_COLLECT_MONEY_SUCCESSFUL';
export const LOAD_DATA_STUDENT_LIST_COLLECT_MONEY_ERROR =
  'LOAD_DATA_STUDENT_LIST_COLLECT_MONEY_ERROR';
export const UPDATE_FORM_SEARCH_STUDENT_LIST_COLLECT_MONEY =
  'UPDATE_FORM_SEARCH_STUDENT_LIST_COLLECT_MONEY';
export const SELECTED_STUDENT_OF_STUDENT_LIST_COLLECT_MONEY =
  'SELECTED_STUDENT_OF_STUDENT_LIST_COLLECT_MONEY';
export const UPDATE_FORM_INFO_MONEY = 'UPDATE_FORM_INFO_MONEY';
export const BEGIN_UPDATE_MONEY_STUDENT_COLLECT_MONEY =
  'BEGIN_UPDATE_MONEY_STUDENT_COLLECT_MONEY';
export const UPDATE_MONEY_STUDENT_COLLECT_MONEY_SUCCESSFUL =
  'UPDATE_MONEY_STUDENT_COLLECT_MONEY_SUCCESSFUL';
export const UPDATE_MONEY_STUDENT_COLLECT_MONEY_ERROR =
  'UPDATE_MONEY_STUDENT_COLLECT_MONEY_ERROR';

export const CHANGE_SEGMENT_MONEY_TRANSFER = 'CHANGE_SEGMENT_MONEY_TRANSFER';
export const BEGIN_DATA_STAFF_OF_MONEY_TRANSFER_LOAD =
  'BEGIN_DATA_STAFF_OF_MONEY_TRANSFER_LOAD';
export const LOAD_DATA_STAFF_OF_MONEY_TRANSFER_SUCCESSFUL =
  'LOAD_DATA_STAFF_OF_MONEY_TRANSFER_SUCCESSFUL';
export const LOAD_DATA_STAFF_OF_MONEY_TRANSFER_ERROR =
  'LOAD_DATA_STAFF_OF_MONEY_TRANSFER_ERROR';
export const UPDATE_FORM_SEARCH_STAFF_LIST = 'UPDATE_FORM_SEARCH_STAFF_LIST';
export const BEGIN_DATA_HISTORY_TRANSACTION_LOAD =
  'BEGIN_DATA_HISTORY_TRANSACTION_LOAD';
export const LOAD_DATA_HISTORY_TRANSACTION_SUCCESSFUL =
  'LOAD_DATA_HISTORY_TRANSACTION_SUCCESSFUL';
export const LOAD_DATA_HISTORY_TRANSACTION_ERROR =
  'LOAD_DATA_HISTORY_TRANSACTION_ERROR';
export const BEGIN_TRANSACTION = 'BEGIN_TRANSACTION';
export const TRANSACTION_SUCCESSFUL = 'TRANSACTION_SUCCESSFUL';
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR';
export const BEGIN_CONFIRM_TRANSACTION = 'BEGIN_CONFIRM_TRANSACTION';
export const CONFIRM_TRANSACTION_SUCCESSFUL = 'CONFIRM_TRANSACTION_SUCCESSFUL';
export const CONFIRM_TRANSACTION_ERROR = 'CONFIRM_TRANSACTION_ERROR';
export const CHANGE_STATUS_TRANSACTION = 'CHANGE_STATUS_TRANSACTION';
export const UPDATE_HISTORY_TRANSACTION_SOCKET =
  'UPDATE_HISTORY_TRANSACTION_SOCKET';

export const BEGIN_DATA_LIST_STUDENT_PAID_LOAD =
  'BEGIN_DATA_LIST_STUDENT_PAID_LOAD';
export const LOAD_DATA_LIST_STUDENT_PAID_SUCCESSFUL =
  'LOAD_DATA_LIST_STUDENT_PAID_SUCCESSFUL';
export const LOAD_DATA_LIST_STUDENT_PAID_ERROR =
  'LOAD_DATA_LIST_STUDENT_PAID_ERROR';

export const BEGIN_DATA_LIST_STUDENT_ZERO_LOAD =
  'BEGIN_DATA_LIST_STUDENT_ZERO_LOAD';
export const LOAD_DATA_LIST_STUDENT_ZERO_SUCCESSFUL =
  'LOAD_DATA_LIST_STUDENT_ZERO_SUCCESSFUL';
export const LOAD_DATA_LIST_STUDENT_ZERO_ERROR =
  'LOAD_DATA_LIST_STUDENT_ZERO_ERROR';

export const BEGIN_CHECK_IN = 'BEGIN_CHECK_IN';
export const CHECK_IN_SUCCESS = 'CHECK_IN_SUCCESS';
export const CHECK_IN_ERROR = 'CHECK_IN_ERROR';

export const BEGIN_DATA_LIST_STUDENT_ATTENDANCE_LOAD =
  'BEGIN_DATA_LIST_STUDENT_ATTENDANCE_LOAD';
export const LOAD_DATA_LIST_STUDENT_ATTENDANCE_SUCCESSFUL =
  'LOAD_DATA_LIST_STUDENT_ATTENDANCE_SUCCESSFUL';
export const LOAD_DATA_LIST_STUDENT_ATTENDANCE_ERROR =
  'LOAD_DATA_LIST_STUDENT_ATTENDANCE_ERROR';

export const BEGIN_LOAD_WORK_SHIFT_DATA = 'BEGIN_LOAD_WORK_SHIFT_DATA';
export const LOAD_WORK_SHIFT_DATA_SUCCESSFUL =
  'LOAD_WORK_SHIFT_DATA_SUCCESSFUL';
export const LOAD_WORK_SHIFT_DATA_ERROR = 'LOAD_WORK_SHIFT_DATA_ERROR';
export const SELECTED_BASE_ID_WORK_SHIFT_REGISTER =
  'SELECTED_BASE_ID_WORK_SHIFT_REGISTER';
export const SELECTED_GEN_ID_WORK_SHIFT_REGISTER =
  'SELECTED_GEN_ID_WORK_SHIFT_REGISTER';
export const BEGIN_WORK_SHIFT_REGISTER = 'BEGIN_WORK_SHIFT_REGISTER';
export const WORK_SHIFT_REGISTER_SUCCESSFUL = 'WORK_SHIFT_REGISTER_SUCCESSFUL';
export const WORK_SHIFT_REGISTER_ERROR = 'WORK_SHIFT_REGISTER_ERROR';
export const WORK_SHIFT_REGISTERING = 'WORK_SHIFT_REGISTERING';
export const BEGIN_WORK_SHIFT_UNREGISTER = 'BEGIN_WORK_SHIFT_UNREGISTER';
export const WORK_SHIFT_UNREGISTER_SUCCESSFUL =
  'WORK_SHIFT_UNREGISTER_SUCCESSFUL';
export const WORK_SHIFT_UNREGISTER_ERROR = 'WORK_SHIFT_UNREGISTER_ERROR';
export const WORK_SHIFT_UNREGISTERING = 'WORK_SHIFT_UNREGISTERING';
