/**
 * Created by phanmduong on 4/5/17.
 */
export const UPDATE_DATA_LOGIN_FORM = 'UPDATE_DATA_LOGIN_FORM';
export const BEGIN_LOGIN = 'BEGIN_LOGIN';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const BEGIN_DATA_BASE_LOAD = 'BEGIN_DATA_BASE_LOAD';
export const LOAD_DATA_BASE_SUCCESSFUL = 'LOAD_DATA_BASE_SUCCESSFUL';
export const LOAD_DATA_BASE_ERROR = 'LOAD_DATA_BASE_ERROR';
export const SELECTED_BASE_ID = 'SELECTED_BASE_ID';

export const BEGIN_DATA_COURSE_LOAD = 'BEGIN_DATA_COURSE_LOAD';
export const LOAD_DATA_COURSE_SUCCESSFUL = 'LOAD_DATA_COURSE_SUCCESSFUL';
export const LOAD_DATA_COURSE_ERROR = 'LOAD_DATA_COURSE_ERROR';
export const SELECTED_COURSE_ID = 'SELECTED_COURSE_ID';
