/**
 * Created by phanmduong on 4/5/17.
 */
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const CHANGE_STATUSBAR_COLOR = 'CHANGE_STATUSBAR_COLOR';

export const UPDATE_DATA_LOGIN_FORM = 'UPDATE_DATA_LOGIN_FORM';
export const BEGIN_LOGIN = 'BEGIN_LOGIN';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const GOT_DATA_LOGIN = 'GOT_DATA_LOGIN';
export const SET_AUTO_LOGIN = 'SET_AUTO_LOGIN';
export const UPDATE_DOMAIN_FORM = 'UPDATE_DOMAIN_FORM';

export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const DISABLE_DRAWER = 'DISABLE_DRAWER';
export const ENABLE_DRAWER = 'ENABLE_DRAWER';

export const BEGIN_DATA_BASE_LOAD = 'BEGIN_DATA_BASE_LOAD';
export const LOAD_DATA_BASE_SUCCESSFUL = 'LOAD_DATA_BASE_SUCCESSFUL';
export const LOAD_DATA_BASE_ERROR = 'LOAD_DATA_BASE_ERROR';
export const SELECTED_BASE_ID = 'SELECTED_BASE_ID';

export const BEGIN_DATA_COURSE_LOAD = 'BEGIN_DATA_COURSE_LOAD';
export const BEGIN_DATA_COURSE_REFRESH = 'BEGIN_DATA_COURSE_REFRESH';
export const LOAD_DATA_COURSE_SUCCESSFUL = 'LOAD_DATA_COURSE_SUCCESSFUL';
export const LOAD_DATA_COURSE_ERROR = 'LOAD_DATA_COURSE_ERROR';
export const SELECTED_COURSE_ID = 'SELECTED_COURSE_ID';
export const BEGIN_DATA_COURSE_SEARCH = 'BEGIN_DATA_COURSE_SEARCH';
export const BEGIN_COURSE_STATUS_CHANGE = 'BEGIN_COURSE_STATUS_CHANGE';
export const COURSE_STATUS_CHANGE_COMPLETE = 'COURSE_STATUS_CHANGE_COMPLETE';
export const BEGIN_LOAD_PARENT_COURSES = 'BEGIN_LOAD_PARENT_COURSES';
export const LOAD_PARENT_COURSES_SUCCESS = 'LOAD_PARENT_COURSES_SUCCESS';
export const LOAD_PARENT_COURSES_ERROR = 'LOAD_PARENT_COURSES_ERROR';
export const BEGIN_CREATE_COURSE = 'BEGIN_CREATE_COURSE';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_COMPLETE = 'CREATE_COURSE_COMPLETE';
export const BEGIN_LOAD_COURSE_DETAILS = 'BEGIN_LOAD_COURSE_DETAILS';
export const BEGIN_REFRESH_COURSE_DETAILS = 'BEGIN_REFRESH_COURSE_DETAILS';
export const LOAD_COURSE_DETAILS_SUCCESS = 'LOAD_COURSE_DETAILS_SUCCESS';
export const LOAD_COURSE_DETAILS_ERROR = 'LOAD_COURSE_DETAILS_ERROR';
export const BEGIN_CHANGE_LESSON_EVENT = 'BEGIN_CHANGE_LESSON_EVENT';
export const CHANGE_LESSON_EVENT_SUCCESS = 'CHANGE_LESSON_EVENT_SUCCESS';
export const CHANGE_LESSON_EVENT_COMPLETE = 'CHANGE_LESSON_EVENT_COMPLETE';
export const BEGIN_DELETE_COURSE_DETAILS_LESSON =
  'BEGIN_DELETE_COURSE_DETAILS_LESSON';
export const DELETE_COURSE_DETAILS_LESSON_SUCCESS =
  'DELETE_COURSE_DETAILS_LESSON_SUCCESS';
export const DELETE_COURSE_DETAILS_LESSON_COMPLETE =
  'DELETE_COURSE_DETAILS_LESSON_COMPLETE';
export const RESET_DATA_COURSE = 'RESET_DATA_COURSE';
export const BEGIN_DUPLICATE_COURSE_DETAILS_LESSON =
  'BEGIN_DUPLICATE_COURSE_DETAILS_LESSON';
export const DUPLICATE_COURSE_DETAILS_LESSON_SUCCESS =
  'DUPLICATE_COURSE_DETAILS_LESSON_SUCCESS';
export const DUPLICATE_COURSE_DETAILS_LESSON_COMPLETE =
  'DUPLICATE_COURSE_DETAILS_LESSON_COMPLETE';
export const BEGIN_ADD_COURSE_DETAILS_LESSON =
  'BEGIN_ADD_COURSE_DETAILS_LESSON';
export const ADD_COURSE_DETAILS_LESSON_SUCCESS =
  'ADD_COURSE_DETAILS_LESSON_SUCCESS';
export const ADD_COURSE_DETAILS_LESSON_COMPLETE =
  'ADD_COURSE_DETAILS_LESSON_COMPLETE';
export const RESET_COURSE_DETAILS = 'RESET_COURSE_DETAILS';
export const BEGIN_EDIT_COURSE_DETAILS_LESSON =
  'BEGIN_EDIT_COURSE_DETAILS_LESSON';
export const EDIT_COURSE_DETAILS_LESSON_COMPLETE =
  'EDIT_COURSE_DETAILS_LESSON_COMPLETE';
export const BEGIN_ADD_COURSE_DETAILS_EXAM = 'BEGIN_ADD_COURSE_DETAILS_EXAM';
export const ADD_COURSE_DETAILS_EXAM_SUCCESS =
  'ADD_COURSE_DETAILS_EXAM_SUCCESS';
export const ADD_COURSE_DETAILS_EXAM_COMPLETE =
  'ADD_COURSE_DETAILS_EXAM_COMPLETE';
export const BEGIN_ADD_COURSE_DETAILS_LINK = 'BEGIN_ADD_COURSE_DETAILS_LINK';
export const ADD_COURSE_DETAILS_LINK_SUCCESS =
  'ADD_COURSE_DETAILS_LINK_SUCCESS';
export const ADD_COURSE_DETAILS_LINK_COMPLETE =
  'ADD_COURSE_DETAILS_LINK_COMPLETE';
export const BEGIN_DELETE_COURSE_DETAILS_LINK =
  'BEGIN_DELETE_COURSE_DETAILS_LINK';
export const DELETE_COURSE_DETAILS_LINK_SUCCESS =
  'DELETE_COURSE_DETAILS_LINK_SUCCESS';
export const DELETE_COURSE_DETAILS_LINK_COMPLETE =
  'DELETE_COURSE_DETAILS_LINK_COMPLETE';

export const BEGIN_DATA_GEN_LOAD = 'BEGIN_DATA_GEN_LOAD';
export const LOAD_DATA_GEN_SUCCESSFUL = 'LOAD_DATA_GEN_SUCCESSFUL';
export const LOAD_DATA_GEN_ERROR = 'LOAD_DATA_GEN_ERROR';
export const SELECTED_GEN_ID = 'SELECTED_GEN_ID';

export const BEGIN_DATA_LESSON_COURSE_LOAD = 'BEGIN_DATA_LESSON_COURSE_LOAD';
export const LOAD_DATA_LESSON_COURSE_SUCCESSFUL =
  'LOAD_DATA_LESSON_COURSE_SUCCESSFUL';
export const LOAD_DATA_LESSON_COURSE_ERROR = 'LOAD_DATA_LESSON_COURSE_ERROR';
export const SELECTED_LESSON_COURSE_ID = 'SELECTED_LESSON_COURSE_ID';

export const BEGIN_DATA_CLASS_LOAD = 'BEGIN_DATA_CLASS_LOAD';
export const LOAD_DATA_CLASS_SUCCESSFUL = 'LOAD_DATA_CLASS_SUCCESSFUL';
export const LOAD_DATA_CLASS_ERROR = 'LOAD_DATA_CLASS_ERROR';
export const BEGIN_DATA_CLASS_REFRESH = 'BEGIN_DATA_CLASS_REFRESH';
export const BEGIN_DATA_COURSES_LOAD = 'BEGIN_DATA_COURSES_LOAD';
export const LOAD_DATA_COURSES_SUCCESSFUL = 'LOAD_DATA_COURSES_SUCCESSFUL';
export const LOAD_DATA_COURSES_ERROR = 'LOAD_DATA_COURSES_ERROR';
export const SELECTED_CLASS_ID = 'SELECTED_CLASS_ID';
export const SELECTED_CLASS_BASE_ID = 'SELECTED_BASE_ID';
export const SELECTED_CLASS_GEN_ID = 'SELECTED_CLASS_GEN_ID';
export const SELECTED_CLASS_COURSE_ID = 'SELECTED_CLASS_COURSE_ID';
export const RESET_CLASS = 'RESET_CLASS';
export const SELECTED_CLASS_STATUS_ID = 'SELECTED_CLASS_STATUS_ID';
export const SELECTED_CLASS_TYPE = 'SELECTED_CLASS_TYPE';
export const SELECTED_CLASS_PROVINCE_ID = 'SELECTED_CLASS_PROVINCE_ID';
export const SELECTED_CLASS_TEACHER_ID = 'SELECTED_CLASS_TEACHER_ID';
export const SELECTED_CLASS_ENROLL_START_TIME =
  'SELECTED_CLASS_ENROLL_START_TIME';
export const SELECTED_CLASS_ENROLL_END_TIME = 'SELECTED_CLASS_ENROLL_END_TIME';
export const SELECTED_CLASS_LESSON_START_TIME =
  'SELECTED_CLASS_LESSON_START_TIME';
export const SELECTED_CLASS_LESSON_END_TIME = 'SELECTED_CLASS_LESSON_END_TIME';
export const SELECTED_CLASS_START_TIME = 'SELECTED_CLASS_START_TIME';
export const SELECTED_CLASS_END_TIME = 'SELECTED_CLASS_END_TIME';
export const SELECTED_CLASS_CLASS_STATUS = 'SELECTED_CLASS_CLASS_STATUS';
export const BEGIN_LOAD_CLASS_STATUSES = 'BEGIN_LOAD_CLASS_STATUSES';
export const LOAD_CLASS_STATUSES_SUCCESS = 'LOAD_CLASS_STATUSES_SUCCESS';
export const LOAD_CLASS_STATUSES_ERROR = 'LOAD_CLASS_STATUSES_ERROR';
export const BEGIN_CREATE_CLASS_SCHEDULE = 'BEGIN_CREATE_CLASS_SCHEDULE';
export const CREATE_CLASS_SCHEDULE_COMPLETE = 'CREATE_CLASS_SCHEDULE_COMPLETE';

export const BEGIN_LOAD_BASE = 'BEGIN_LOAD_BASE';
export const LOAD_BASE_SUCCESSFUL = 'LOAD_BASE_SUCCESSFUL';
export const LOAD_BASE_ERROR = 'LOAD_BASE_ERROR';
export const BEGIN_LOAD_INFO_CREATE_CLASS = 'BEGIN_LOAD_INFO_CREATE_CLASS';
export const LOAD_INFO_CREATE_CLASS_SUCCESSFUL =
  'LOAD_INFO_CREATE_CLASS_SUCCESSFUL';
export const LOAD_INFO_CREATE_CLASS_ERROR = 'LOAD_INFO_CREATE_CLASS_ERROR';
export const BEGIN_ADD_CLASS = 'BEGIN_ADD_CLASS';
export const ADD_CLASS_SUCCESSFUL = 'ADD_CLASS_SUCCESSFUL';
export const ADD_CLASS_ERROR = 'ADD_CLASS_ERROR';
export const BEGIN_LOAD_CLASS_INFO = 'BEGIN_LOAD_CLASS_INFO';
export const LOAD_CLASS_INFO_SUCCESSFUL = 'LOAD_CLASS_INFO_SUCCESSFUL';
export const LOAD_CLASS_INFO_ERROR = 'LOAD_CLASS_INFO_ERROR';
export const BEGIN_CHANGE_CLASS_STATUS = 'BEGIN_CHANGE_CLASS_STATUS';
export const CHANGE_CLASS_STATUS_SUCCESSFUL = '';
export const CHANGE_CLASS_STATUS_ERROR = '';
export const BEGIN_SEARCH_CLASS = 'BEGIN_SEARCH_CLASS';

export const BEGIN_DATA_CURRENT_CLASS_STUDY_LOAD =
  'BEGIN_DATA_CURRENT_CLASS_STUDY_LOAD';
export const BEGIN_DATA_CURRENT_CLASS_STUDY_REFRESH =
  'BEGIN_DATA_CURRENT_CLASS_STUDY_REFRESH';
export const LOAD_DATA_CURRENT_CLASS_STUDY_SUCCESSFUL =
  'LOAD_DATA_CURRENT_CLASS_STUDY_SUCCESSFUL';
export const LOAD_DATA_CURRENT_CLASS_STUDY_ERROR =
  'LOAD_DATA_CURRENT_CLASS_STUDY_ERROR';
export const SELECTED_CURRENT_CLASS_STUDY = 'SELECTED_CURRENT_CLASS_STUDY';
export const ON_SELECT_CLASS_DATE = 'ON_SELECT_CLASS_DATE';

export const BEGIN_SCAN_QR_CODE = 'BEGIN_SCAN_QR_CODE';
export const SCANNED_QR_CODE = 'SCANNED_QR_CODE';
export const IS_SCANNED_QR_CODE = 'IS_SCANNED_QR_CODE';

export const BEGIN_GET_INFOR_STUDENT = 'BEGIN_GET_INFOR_STUDENT';
export const LOAD_GET_INFOR_STUDENT_SUCCESSFUL =
  'LOAD_GET_INFOR_STUDENT_SUCCESSFUL';
export const LOAD_GET_INFOR_STUDENT_ERROR = 'LOAD_GET_INFOR_STUDENT_ERROR';
export const BEGIN_POST_ATTENDANCE_STUDENT = 'BEGIN_POST_ATTENDANCE_STUDENT';
export const LOAD_POST_ATTENDANCE_STUDENT_SUCCESSFUL =
  'LOAD_POST_ATTENDANCE_STUDENT_SUCCESSFUL';
export const LOAD_POST_ATTENDANCE_STUDENT_ERROR =
  'LOAD_POST_ATTENDANCE_STUDENT_ERROR';
export const BEGIN_UNBLOCK_STUDENT = 'BEGIN_UNBLOCK_STUDENT';
export const LOAD_UNBLOCKING_STUDENT = 'LOAD_UNBLOCKING_STUDENT';
export const ERROR_UNBLOCKING_STUDENT = 'ERROR_UNBLOCKING_STUDENT';
export const BEGIN_UPLOAD_IMAGE_STUDENT = 'BEGIN_UPLOAD_IMAGE_STUDENT';
export const UPLOAD_IMAGE_STUDENT = 'UPLOAD_IMAGE_STUDENT';
export const BEGIN_CHANGE_CLASS_ATTENDANCE = 'BEGIN_CHANGE_CLASS_ATTENDANCE';
export const CHANGE_CLASS_ATTENDANCE_SUCCESSFUL =
  'CHANGE_CLASS_ATTENDANCE_SUCCESSFUL';
export const CHANGE_CLASS_ATTENDANCE_ERROR = 'CHANGE_CLASS_ATTENDANCE_ERROR';

export const HISTORY_TEACHING_TAB = 'HISTORY_TEACHING_TAB';
export const HISTORY_WORK_SHIFT_TAB = 'HISTORY_WORK_SHIFT_TAB';
export const HISTORY_SHIFT_TAB = 'HISTORY_SHIFT_TAB';

export const BEGIN_DATA_SHIFT_REGISTER_LOAD = 'BEGIN_DATA_SHIFT_REGISTER_LOAD';
export const LOAD_DATA_SHIFT_REGISTER_SUCCESSFUL =
  'LOAD_DATA_SHIFT_REGISTER_SUCCESSFUL';
export const LOAD_DATA_SHIFT_REGISTER_ERROR = 'LOAD_DATA_SHIFT_REGISTER_ERROR';
export const POST_SHIFT_REGISTER = 'POST_SHIFT_REGISTER';
export const SHIFT_REGISTER_SUCCESSFUL = 'SHIFT_REGISTER_SUCCESSFUL';
export const SHIFT_REGISTER_ERROR = 'SHIFT_REGISTER_ERROR';
export const POST_SHIFT_UNREGISTER = 'POST_SHIFT_UNREGISTER';
export const SHIFT_UNREGISTER_SUCCESSFUL = 'SHIFT_UNREGISTER_SUCCESSFUL';
export const SHIFT_UNREGISTER_ERROR = 'SHIFT_UNREGISTER_ERROR';
export const SELECTED_BASE_ID_SHIFT_REGISTER =
  'SELECTED_BASE_ID_SHIFT_REGISTER';
export const SELECTED_GEN_ID_SHIFT_REGISTER = 'SELECTED_GEN_ID_SHIFT_REGISTER';
export const UPDATE_DATA_SHIFT_REGISTER = 'UPDATE_DATA_SHIFT_REGISTER';

export const BEGIN_DATA_ANALYTICS_REGISTER_LOAD =
  'BEGIN_DATA_ANALYTICS_REGISTER_LOAD';
export const LOAD_DATA_ANALYTICS_REGISTER_SUCCESSFUL =
  'LOAD_DATA_ANALYTICS_REGISTER_SUCCESSFUL';
export const LOAD_DATA_ANALYTICS_REGISTER_ERROR =
  'LOAD_DATA_ANALYTICS_REGISTER_ERROR';
export const BEGIN_DATA_ANALYTICS_REGISTER_REFRESH =
  'BEGIN_DATA_ANALYTICS_REGISTER_REFRESH';
export const BEGIN_DATA_ANALYTICS_REVENUE_LOAD =
  'BEGIN_DATA_ANALYTICS_REVENUE_LOAD';
export const LOAD_DATA_ANALYTICS_REVENUE_SUCCESSFUL =
  'LOAD_DATA_ANALYTICS_REVENUE_SUCCESSFUL';
export const LOAD_DATA_ANALYTICS_REVENUE_ERROR =
  'LOAD_DATA_ANALYTICS_REVENUE_ERROR';
export const BEGIN_DATA_ANALYTICS_REVENUE_REFRESH =
  'BEGIN_DATA_ANALYTICS_REVENUE_REFRESH';
export const BEGIN_DATA_ANALYTICS_KPI_LOAD = 'BEGIN_DATA_ANALYTICS_KPI_LOAD';
export const BEGIN_DATA_ANALYTICS_CLASSES_LOAD =
  'BEGIN_DATA_ANALYTICS_CLASSES_LOAD';
export const LOAD_DATA_ANALYTICS_CLASSES_SUCCESSFUL =
  'LOAD_DATA_ANALYTICS_CLASSES_SUCCESSFUL';
export const LOAD_DATA_ANALYTICS_CLASSES_ERROR =
  'LOAD_DATA_ANALYTICS_CLASSES_ERROR';
export const BEGIN_DATA_ANALYTICS_CLASSES_REFRESH =
  'BEGIN_DATA_ANALYTICS_CLASSES_REFRESH';
export const SELECTED_BASE_ID_ANALYTICS = 'SELECTED_BASE_ID_ANALYTICS';
export const SELECTED_GEN_ID_ANALYTICS = 'SELECTED_GEN_ID_ANALYTICS';
export const SELECTED_START_DATE_ANALYTICS = 'SELECTED_START_DATE_ANALYTICS';
export const SELECTED_END_DATE_ANALYTICS = 'SELECTED_END_DATE_ANALYTICS';
export const SELECTED_STAFF_ID_ANALYTICS = 'SELECTED_STAFF_ID_ANALYTICS';
export const SELECTED_COURSE_ID_ANALYTICS = 'SELECTED_COURSE_ID_ANALYTICS';
export const SELECTED_CAMPAIGN_ID_ANALYTICS = 'SELECTED_CAMPAIGN_ID_ANALYTICS';
export const SELECTED_SOURCE_ID_ANALYTICS = 'SELECTED_SOURCE_ID_ANALYTICS';
export const SELECTED_CLASS_TYPE_ANALYTICS = 'SELECTED_CLASS_TYPE_ANALYTICS';
export const SELECTED_PROVINCE_ID_ANALYTICS = 'SELECTED_PROVINCE_ID_ANALYTICS';
export const BEGIN_CHANGE_PROVINCE = 'BEGIN_CHANGE_PROVINCE_ANALYTICS';

export const BEGIN_DATA_LIST_STUDENT_CLASS_LOAD =
  'BEGIN_DATA_LIST_STUDENT_CLASS_LOAD';
export const BEGIN_DATA_LIST_STUDENT_CLASS_REFRESH =
  'BEGIN_DATA_LIST_STUDENT_CLASS_REFRESH';
export const LOAD_DATA_LIST_STUDENT_CLASS_SUCCESSFUL =
  'LOAD_DATA_LIST_STUDENT_CLASS_SUCCESSFUL';
export const LOAD_DATA_LIST_STUDENT_CLASS_ERROR =
  'LOAD_DATA_LIST_STUDENT_CLASS_ERROR';
export const BEGIN_LOAD_LIST_STUDENT_CLASS_LESSONS =
  'BEGIN_LOAD_LIST_STUDENT_CLASS_LESSONS';
export const BEGIN_REFRESH_LIST_STUDENT_CLASS_LESSONS =
  'BEGIN_REFRESH_LIST_STUDENT_CLASS_LESSONS';
export const LOAD_LIST_STUDENT_CLASS_LESSONS_SUCCESSFUL =
  'LOAD_LIST_STUDENT_CLASS_LESSONS_SUCCESSFUL';
export const LOAD_LIST_STUDENT_CLASS_LESSONS_ERROR =
  'LOAD_LIST_STUDENT_CLASS_LESSONS_ERROR';
export const RESET_LIST_STUDENT_CLASS = 'RESET_LIST_STUDENT_CLASS';
export const BEGIN_CHANGE_CLASS_LESSONS = 'BEGIN_CHANGE_CLASS_LESSONS';
export const CHANGE_CLASS_LESSONS_SUCCESS = 'CHANGE_CLASS_LESSONS_SUCCESS';
export const CHANGE_CLASS_LESSONS_ERROR = 'CHANGE_CLASS_LESSONS_ERROR';
export const BEGIN_CHANGE_CLASS_LESSON = 'BEGIN_CHANGE_CLASS_LESSON';
export const CHANGE_CLASS_LESSON_SUCCESS = 'CHANGE_CLASS_LESSON_SUCCESS';
export const CHANGE_CLASS_LESSON_ERROR = 'CHANGE_CLASS_LESSON_ERROR';
export const BEGIN_CHANGE_CLASS_TEACHER = 'BEGIN_CHANGE_CLASS_TEACHER';
export const CHANGE_CLASS_TEACHER_SUCCESS = 'CHANGE_CLASS_TEACHER_SUCCESS';
export const CHANGE_CLASS_TEACHER_ERROR = 'CHANGE_CLASS_TEACHER_ERROR';
export const BEGIN_CHANGE_CLASS_ASSIST = 'BEGIN_CHANGE_CLASS_ASSIST';
export const CHANGE_CLASS_ASSIST_SUCCESS = 'CHANGE_CLASS_ASSIST_SUCCESS';
export const CHANGE_CLASS_ASSIST_ERROR = 'CHANGE_CLASS_ASSIST_ERROR';

export const BEGIN_DATA_REGISTER_LIST_LOAD_MY =
  'BEGIN_DATA_REGISTER_LIST_LOAD_MY';
export const LOAD_DATA_REGISTER_LIST_SUCCESSFUL_MY =
  'LOAD_DATA_REGISTER_LIST_SUCCESSFUL_MY';
export const LOAD_DATA_REGISTER_LIST_ERROR_MY =
  'LOAD_DATA_REGISTER_LIST_ERROR_MY';
export const UPDATE_FORM_SEARCH_REGISTER_LIST_MY =
  'UPDATE_FORM_SEARCH_REGISTER_LIST_MY';
export const RESET_PAGE_REGISTER_LIST_MY = 'RESET_PAGE_REGISTER_LIST_MY';
export const SELECT_REGISTER_LIST_SALER = 'SELECT_REGISTER_LIST_SALER';
export const SELECT_REGISTER_LIST_CAMPAIGN = 'SELECT_REGISTER_LIST_CAMPAIGN';
export const SELECT_REGISTER_LIST_PAID_STATUS =
  'SELECT_REGISTER_LIST_PAID_STATUS';
export const SELECT_REGISTER_LIST_CLASS_STATUS =
  'SELECT_REGISTER_LIST_CLASS_STATUS';
export const SELECT_REGISTER_LIST_CALL_STATUS =
  'SELECT_REGISTER_LIST_CALL_STATUS';
export const SELECT_REGISTER_LIST_BOOKMARK = 'SELECT_REGISTER_LIST_BOOKMARK';
export const SELECT_REGISTER_LIST_START_TIME =
  'SELECT_REGISTER_LIST_START_TIME';
export const SELECT_REGISTER_LIST_END_TIME = 'SELECT_REGISTER_LIST_END_TIME';
export const SELECT_REGISTER_LIST_APPOINTMENT_PAYMENT_START_TIME =
  'SELECT_REGISTER_LIST_APPOINTMENT_PAYMENT_START_TIME';
export const SELECT_REGISTER_LIST_APPOINTMENT_PAYMENT_END_TIME =
  'SELECT_REGISTER_LIST_APPOINTMENT_PAYMENT_END_TIME';
export const SELECT_REGISTER_LIST_SOURCE = 'SELECT_REGISTER_LIST_SOURCE';
export const SELECT_REGISTER_LIST_STATUS = 'SELECT_REGISTER_LIST_STATUS';
export const SELECT_REGISTER_LIST_CLASS = 'SELECT_REGISTER_LIST_CLASS';
export const SET_AUTOFOCUS_REGISTER_LIST_SEARCH =
  'SET_AUTOFOCUS_REGISTER_LIST_SEARCH';
export const BEGIN_LOAD_REGISTER_LIST_AVAILABLE_CLASSES =
  'BEGIN_LOAD_REGISTER_LIST_AVAILABLE_CLASSES';
export const LOAD_REGISTER_LIST_AVAILABLE_CLASSES_SUCCESSFUL =
  'LOAD_REGISTER_LIST_AVAILABLE_CLASSES_SUCCESSFUL';
export const LOAD_REGISTER_LIST_AVAILABLE_CLASSES_ERROR =
  'LOAD_REGISTER_LIST_AVAILABLE_CLASSES_ERROR';
export const RESET_REGISTER_LIST_AVAILABLE_CLASSES =
  'RESET_REGISTER_LIST_AVAILABLE_CLASSES';
export const BEGIN_CHANGE_STUDENT_CLASS = 'BEGIN_CHANGE_STUDENT_CLASS';
export const CHANGE_STUDENT_CLASS_SUCCESSFUL =
  'CHANGE_STUDENT_CLASS_SUCCESSFUL';
export const CHANGE_STUDENT_CLASS_ERROR = 'CHANGE_STUDENT_CLASS_ERROR';
export const BEGIN_LOAD_REGISTER_LIST_COURSES =
  'BEGIN_REGISTER_LIST_LOAD_COURSES';
export const LOAD_REGISTER_LIST_COURSES_SUCCESSFUL =
  'LOAD_REGISTER_LIST_COURSES_SUCCESSFUL';
export const LOAD_REGISTER_LIST_COURSES_ERROR =
  'LOAD_REGISTER_LIST_COURSES_ERROR';
export const SELECT_REGISTER_LIST_COURSE = 'SELECT_REGISTER_LIST_COURSE';
export const SELECT_REGISTER_LIST_DATE_TEST = 'SELECT_REGISTER_LIST_DATE_TEST';
export const SELECT_REGISTER_LIST_CALL_BACK_START_TIME =
  'SELECT_REGISTER_LIST_CALL_BACK_START_TIME';
export const SELECT_REGISTER_LIST_CALL_BACK_END_TIME =
  'SELECT_REGISTER_LIST_CALL_BACK_END_TIME';
export const SELECT_REGISTER_LIST_BASE = 'SELECT_REGISTER_LIST_BASE';
export const SELECT_REGISTER_LIST_PROVINCE = 'SELECT_REGISTER_LIST_PROVINCE';
export const SELECT_REGISTER_LIST_COUPON = 'SELECT_REGISTER_LIST_COUPON';
export const CHANGE_REGISTER_LIST_NOTE = 'CHANGE_REGISTER_LIST_NOTE';

export const BEGIN_DATA_STUDENT_LIST_COLLECT_MONEY_LOAD =
  'BEGIN_DATA_STUDENT_LIST_COLLECT_MONEY_LOAD';
export const BEGIN_DATA_STUDENT_LIST_COLLECT_MONEY_REFRESH =
  'BEGIN_DATA_STUDENT_LIST_COLLECT_MONEY_REFRESH';
export const LOAD_DATA_STUDENT_LIST_COLLECT_MONEY_SUCCESSFUL =
  'LOAD_DATA_STUDENT_LIST_COLLECT_MONEY_SUCCESSFUL';
export const LOAD_DATA_STUDENT_LIST_COLLECT_MONEY_ERROR =
  'LOAD_DATA_STUDENT_LIST_COLLECT_MONEY_ERROR';
export const UPDATE_FORM_SEARCH_STUDENT_LIST_COLLECT_MONEY =
  'UPDATE_FORM_SEARCH_STUDENT_LIST_COLLECT_MONEY';
export const SELECTED_STUDENT_OF_STUDENT_LIST_COLLECT_MONEY =
  'SELECTED_STUDENT_OF_STUDENT_LIST_COLLECT_MONEY';
export const UPDATE_FORM_INFO_MONEY = 'UPDATE_FORM_INFO_MONEY';
export const BEGIN_UPDATE_MONEY_STUDENT_COLLECT_MONEY =
  'BEGIN_UPDATE_MONEY_STUDENT_COLLECT_MONEY';
export const UPDATE_MONEY_STUDENT_COLLECT_MONEY_SUCCESSFUL =
  'UPDATE_MONEY_STUDENT_COLLECT_MONEY_SUCCESSFUL';
export const UPDATE_MONEY_STUDENT_COLLECT_MONEY_ERROR =
  'UPDATE_MONEY_STUDENT_COLLECT_MONEY_ERROR';

export const CHANGE_SEGMENT_MONEY_TRANSFER = 'CHANGE_SEGMENT_MONEY_TRANSFER';
export const BEGIN_DATA_STAFF_OF_MONEY_TRANSFER_LOAD =
  'BEGIN_DATA_STAFF_OF_MONEY_TRANSFER_LOAD';
export const BEGIN_DATA_STAFF_OF_MONEY_TRANSFER_REFRESH =
  'BEGIN_DATA_STAFF_OF_MONEY_TRANSFER_REFRESH';
export const LOAD_DATA_STAFF_OF_MONEY_TRANSFER_SUCCESSFUL =
  'LOAD_DATA_STAFF_OF_MONEY_TRANSFER_SUCCESSFUL';
export const LOAD_DATA_STAFF_OF_MONEY_TRANSFER_ERROR =
  'LOAD_DATA_STAFF_OF_MONEY_TRANSFER_ERROR';
export const UPDATE_FORM_SEARCH_STAFF_LIST = 'UPDATE_FORM_SEARCH_STAFF_LIST';
export const BEGIN_DATA_HISTORY_TRANSACTION_LOAD =
  'BEGIN_DATA_HISTORY_TRANSACTION_LOAD';
export const LOAD_DATA_HISTORY_TRANSACTION_SUCCESSFUL =
  'LOAD_DATA_HISTORY_TRANSACTION_SUCCESSFUL';
export const LOAD_DATA_HISTORY_TRANSACTION_ERROR =
  'LOAD_DATA_HISTORY_TRANSACTION_ERROR';
export const BEGIN_TRANSACTION = 'BEGIN_TRANSACTION';
export const TRANSACTION_SUCCESSFUL = 'TRANSACTION_SUCCESSFUL';
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR';
export const BEGIN_CONFIRM_TRANSACTION = 'BEGIN_CONFIRM_TRANSACTION';
export const CONFIRM_TRANSACTION_SUCCESSFUL = 'CONFIRM_TRANSACTION_SUCCESSFUL';
export const CONFIRM_TRANSACTION_ERROR = 'CONFIRM_TRANSACTION_ERROR';
export const CHANGE_STATUS_TRANSACTION = 'CHANGE_STATUS_TRANSACTION';
export const UPDATE_HISTORY_TRANSACTION_SOCKET =
  'UPDATE_HISTORY_TRANSACTION_SOCKET';
export const BEGIN_LOAD_DOMAINS = 'BEGIN_LOAD_DOMAINS';
export const LOAD_DOMAINS_SUCCESSFUL = 'LOAD_DOMAINS_SUCCESSFUL';
export const LOAD_DOMAINS_ERROR = 'LOAD_DOMAINS_ERROR';

export const BEGIN_DATA_LIST_STUDENT_PAID_LOAD =
  'BEGIN_DATA_LIST_STUDENT_PAID_LOAD';
export const LOAD_DATA_LIST_STUDENT_PAID_SUCCESSFUL =
  'LOAD_DATA_LIST_STUDENT_PAID_SUCCESSFUL';
export const LOAD_DATA_LIST_STUDENT_PAID_ERROR =
  'LOAD_DATA_LIST_STUDENT_PAID_ERROR';

export const BEGIN_DATA_LIST_STUDENT_ZERO_LOAD =
  'BEGIN_DATA_LIST_STUDENT_ZERO_LOAD';
export const LOAD_DATA_LIST_STUDENT_ZERO_SUCCESSFUL =
  'LOAD_DATA_LIST_STUDENT_ZERO_SUCCESSFUL';
export const LOAD_DATA_LIST_STUDENT_ZERO_ERROR =
  'LOAD_DATA_LIST_STUDENT_ZERO_ERROR';

export const BEGIN_CHECK_IN = 'BEGIN_CHECK_IN';
export const CHECK_IN_SUCCESS = 'CHECK_IN_SUCCESS';
export const CHECK_IN_ERROR = 'CHECK_IN_ERROR';

export const BEGIN_DATA_LIST_STUDENT_ATTENDANCE_LOAD =
  'BEGIN_DATA_LIST_STUDENT_ATTENDANCE_LOAD';
export const LOAD_DATA_LIST_STUDENT_ATTENDANCE_SUCCESSFUL =
  'LOAD_DATA_LIST_STUDENT_ATTENDANCE_SUCCESSFUL';
export const LOAD_DATA_LIST_STUDENT_ATTENDANCE_ERROR =
  'LOAD_DATA_LIST_STUDENT_ATTENDANCE_ERROR';

export const BEGIN_LOAD_WORK_SHIFT_DATA = 'BEGIN_LOAD_WORK_SHIFT_DATA';
export const LOAD_WORK_SHIFT_DATA_SUCCESSFUL =
  'LOAD_WORK_SHIFT_DATA_SUCCESSFUL';
export const LOAD_WORK_SHIFT_DATA_ERROR = 'LOAD_WORK_SHIFT_DATA_ERROR';
export const SELECTED_BASE_ID_WORK_SHIFT_REGISTER =
  'SELECTED_BASE_ID_WORK_SHIFT_REGISTER';
export const SELECTED_GEN_ID_WORK_SHIFT_REGISTER =
  'SELECTED_GEN_ID_WORK_SHIFT_REGISTER';
export const BEGIN_WORK_SHIFT_REGISTER = 'BEGIN_WORK_SHIFT_REGISTER';
export const WORK_SHIFT_REGISTER_SUCCESSFUL = 'WORK_SHIFT_REGISTER_SUCCESSFUL';
export const WORK_SHIFT_REGISTER_ERROR = 'WORK_SHIFT_REGISTER_ERROR';
export const WORK_SHIFT_REGISTERING = 'WORK_SHIFT_REGISTERING';
export const BEGIN_WORK_SHIFT_UNREGISTER = 'BEGIN_WORK_SHIFT_UNREGISTER';
export const WORK_SHIFT_UNREGISTER_SUCCESSFUL =
  'WORK_SHIFT_UNREGISTER_SUCCESSFUL';
export const WORK_SHIFT_UNREGISTER_ERROR = 'WORK_SHIFT_UNREGISTER_ERROR';
export const WORK_SHIFT_UNREGISTERING = 'WORK_SHIFT_UNREGISTERING';

export const BEGIN_LOAD_TEACHER_RATING = 'BEGIN_LOAD_TEACHER_RATING';
export const LOAD_TEACHER_RATING_SUCCESSFUL = 'LOAD_TEACHER_RATING_SUCCESSFUL';
export const LOAD_TEACHER_RATING_ERROR = 'LOAD_TEACHER_RATING_ERROR';
export const BEGIN_LOAD_ASSISTANT_RATING = 'BEGIN_LOAD_ASSISTANT_RATING';
export const LOAD_ASSISTANT_RATING_SUCCESSFUL =
  'LOAD_ASSISTANT_RATING_SUCCESSFUL';
export const LOAD_ASSISTANT_RATING_ERROR = 'LOAD_ASSISTANT_RATING_ERROR';
export const SELECTED_GEN_ID_RATING = 'SELECTED_GEN_ID_RATING';
export const BEGIN_LOAD_TEACHER_FEEDBACK = 'BEGIN_LOAD_TEACHER_FEEDBACK';
export const LOAD_TEACHER_FEEDBACK_SUCCESSFUL =
  'LOAD_TEACHER_FEEDBACK_SUCCESSFUL';
export const LOAD_TEACHER_FEEDBACK_ERROR = 'LOAD_TEACHER_FEEDBACK_ERROR';
export const BEGIN_LOAD_ASSISTANT_FEEDBACK = 'BEGIN_LOAD_ASSISTANT_FEEDBACK';
export const LOAD_ASSISTANT_FEEDBACK_SUCCESSFUL =
  'LOAD_ASSISTANT_FEEDBACK_SUCCESSFUL';
export const LOAD_ASSISTANT_FEEDBACK_ERROR = 'LOAD_ASSISTANT_FEEDBACK_ERROR';

export const BEGIN_LOAD_TEACHER_LIST = 'BEGIN_LOAD_TEACHER_LIST';
export const LOAD_TEACHER_LIST_SUCCESSFUL = 'LOAD_TEACHER_LIST_SUCCESSFUL';
export const LOAD_TEACHER_LIST_ERROR = 'LOAD_TEACHER_LIST_ERROR';
export const BEGIN_LOAD_ASSISTANT_LIST = 'BEGIN_LOAD_ASSISTANT_LIST';
export const LOAD_ASSISTANT_LIST_SUCCESSFUL = 'LOAD_ASSISTANT_LIST_SUCCESSFUL';
export const LOAD_ASSISTANT_LIST_ERROR = 'LOAD_ASSISTANT_LIST_ERROR';
export const SELECTED_GEN_ID_TEACHING_TEAM_LIST =
  'SELECTED_GEN_ID_TEACHING_TEAM_LIST';

export const BEGIN_LOAD_TEACHER_RATING_DUPLICATE =
  'BEGIN_LOAD_TEACHER_RATING_DUPLICATE';
export const LOAD_TEACHER_RATING_SUCCESSFUL_DUPLICATE =
  'LOAD_TEACHER_RATING_SUCCESSFUL_DUPLICATE';
export const LOAD_TEACHER_RATING_ERROR_DUPLICATE =
  'LOAD_TEACHER_RATING_ERROR_DUPLICATE';
export const BEGIN_LOAD_ASSISTANT_RATING_DUPLICATE =
  'BEGIN_LOAD_ASSISTANT_RATING_DUPLICATE';
export const LOAD_ASSISTANT_RATING_SUCCESSFUL_DUPLICATE =
  'LOAD_ASSISTANT_RATING_SUCCESSFUL_DUPLICATE';
export const LOAD_ASSISTANT_RATING_ERROR_DUPLICATE =
  'LOAD_ASSISTANT_RATING_ERROR_DUPLICATE';
export const SELECTED_GEN_ID_RATING_DUPLICATE =
  'SELECTED_GEN_ID_RATING_DUPLICATE';
export const BEGIN_LOAD_TEACHER_FEEDBACK_DUPLICATE =
  'BEGIN_LOAD_TEACHER_FEEDBACK_DUPLICATE';
export const LOAD_TEACHER_FEEDBACK_SUCCESSFUL_DUPLICATE =
  'LOAD_TEACHER_FEEDBACK_SUCCESSFUL_DUPLICATE';
export const LOAD_TEACHER_FEEDBACK_ERROR_DUPLICATE =
  'LOAD_TEACHER_FEEDBACK_ERROR_DUPLICATE';
export const BEGIN_LOAD_ASSISTANT_FEEDBACK_DUPLICATE =
  'BEGIN_LOAD_ASSISTANT_FEEDBACK_DUPLICATE';
export const LOAD_ASSISTANT_FEEDBACK_SUCCESSFUL_DUPLICATE =
  'LOAD_ASSISTANT_FEEDBACK_SUCCESSFUL_DUPLICATE';
export const LOAD_ASSISTANT_FEEDBACK_ERROR_DUPLICATE =
  'LOAD_ASSISTANT_FEEDBACK_ERROR_DUPLICATE';

export const BEGIN_LOAD_DETAIL_SHIFTS = 'BEGIN_LOAD_DETAIL_SHIFTS';
export const LOAD_DETAIL_SHIFTS_SUCCESSFUL = 'LOAD_DETAIL_SHIFTS_SUCCESSFUL';
export const LOAD_DETAIL_SHIFTS_ERROR = 'LOAD_DETAIL_SHIFTS_ERROR';

export const BEGIN_LOAD_SCHEDULE_CLASSES = 'BEGIN_LOAD_SCHEDULE_CLASSES';
export const LOAD_SCHEDULE_CLASSES_SUCCESSFUL =
  'LOAD_SCHEDULE_CLASSES_SUCCESSFUL';
export const LOAD_SCHEDULE_CLASSES_ERROR = 'LOAD_SCHEDULE_CLASSES_ERROR';
export const BEGIN_LOAD_ALL_COURSES = 'BEGIN_LOAD_ALL_COURSES';
export const LOAD_ALL_COURSES_SUCCESSFUL = 'LOAD_ALL_COURSES_SUCCESSFUL';
export const LOAD_ALL_COURSES_ERROR = 'LOAD_ALL_COURSES_ERROR';
export const RESET_SCHEDULE_CLASSES = 'RESET_SCHEDULE_CLASSES';

export const BEGIN_LOAD_COURSES = 'BEGIN_LOAD_COURSES';
export const LOAD_COURSES_SUCCESSFUL = 'LOAD_COURSES_SUCCESSFUL';
export const LOAD_COURSES_ERROR = 'LOAD_COURSES_ERROR';
export const BEGIN_LOAD_REGISTER_CLASSES = 'BEGIN_LOAD_REGISTER_CLASSES';
export const LOAD_REGISTER_CLASSES_SUCCESSFUL =
  'LOAD_REGISTER_CLASSES_SUCCESSFUL';
export const LOAD_REGISTER_CLASSES_ERROR = 'LOAD_REGISTER_CLASSES_ERROR';
export const BEGIN_REGISTER_STUDENT = 'BEGIN_REGISTER_STUDENT';
export const REGISTER_STUDENT_SUCCESSFUL = 'REGISTER_STUDENT_SUCCESSFUL';
export const REGISTER_STUDENT_ERROR = 'REGISTER_STUDENT_ERROR';
export const BEGIN_LOAD_CAMPAIGNS = 'BEGIN_LOAD_CAMPAIGNS';
export const LOAD_CAMPAIGNS_SUCCESSFUL = 'LOAD_CAMPAIGNS_SUCCESSFUL';
export const LOAD_CAMPAIGNS_ERROR = 'LOAD_CAMPAIGNS_ERROR';
export const BEGIN_LOAD_PROVINCES = 'BEGIN_LOAD_PROVINCES';
export const LOAD_PROVINCES_SUCCESSFUL = 'LOAD_PROVINCES_SUCCESSFUL';
export const LOAD_PROVINCES_ERROR = 'LOAD_PROVINCES_ERROR';
export const BEGIN_LOAD_SOURCES = 'BEGIN_LOAD_SOURCES';
export const LOAD_SOURCES_SUCCESSFUL = 'LOAD_SOURCES_SUCCESSFUL';
export const LOAD_SOURCES_ERROR = 'LOAD_SOURCES_ERROR';
export const BEGIN_LOAD_STATUSES = 'BEGIN_LOAD_STATUSES';
export const LOAD_STATUSES_SUCCESSFUL = 'LOAD_STATUSES_SUCCESSFUL';
export const LOAD_STATUSES_ERROR = 'LOAD_STATUSES_ERROR';
export const BEGIN_LOAD_SALERS = 'BEGIN_LOAD_SALERS';
export const LOAD_SALERS_SUCCESSFUL = 'LOAD_SALERS_SUCCESSFUL';
export const LOAD_SALERS_ERROR = 'LOAD_SALERS_ERROR';
export const BEGIN_LOAD_FILTER_CLASSES = 'BEGIN_LOAD_FILTER_CLASSES';
export const LOAD_FILTER_CLASSES_SUCCESSFUL = 'LOAD_FILTER_CLASSES_SUCCESSFUL';
export const LOAD_FILTER_CLASSES_ERROR = 'LOAD_FILTER_CLASSES_ERROR';
export const BEGIN_LOAD_COUPONS = 'BEGIN_LOAD_COUPONS';
export const LOAD_COUPONS_SUCCESS = 'LOAD_COUPONS_SUCCESS';
export const LOAD_COUPONS_ERROR = 'LOAD_COUPONS_ERROR';
export const RESET_CREATED_REGISTER = 'RESET_CREATED_REGISTER';

export const INFO_STUDENT_SET_STUDENT_ID = 'INFO_STUDENT_SET_STUDENT_ID';
export const BEGIN_LOAD_INFO_STUDENT_REGISTERS =
  'BEGIN_LOAD_INFO_STUDENT_REGISTERS';
export const BEGIN_REFRESH_INFO_STUDENT_REGISTERS =
  'BEGIN_REFRESH_INFO_STUDENT_REGISTERS';
export const LOAD_INFO_STUDENT_REGISTERS_SUCCESSFUL =
  'LOAD_INFO_STUDENT_REGISTERS_SUCCESSFUL';
export const LOAD_INFO_STUDENT_REGISTERS_ERROR =
  'LOAD_INFO_STUDENT_REGISTERS_ERROR';

export const INFO_STUDENT_REGISTERS_TAB = 'INFO_STUDENT_REGISTERS_TAB';
export const INFO_STUDENT_HISTORY_CALLS_TAB = 'INFO_STUDENT_HISTORY_CALLS_TAB';
export const INFO_STUDENT_PROGRESS_TAB = 'INFO_STUDENT_PROGRESS_TAB';
export const INFO_STUDENT_HISTORY_COLLECT_MONEY_TAB =
  'INFO_STUDENT_HISTORY_COLLECT_MONEY_TAB';
export const BEGIN_LOAD_CHANGE_CALL_STATUS = 'BEGIN_LOAD_CHANGE_CALL_STATUS';
export const LOAD_CHANGE_CALL_STATUS_SUCCESSFUL =
  'LOAD_CHANGE_CALL_STATUS_SUCCESSFUL';
export const LOAD_CHANGE_CALL_STATUS_ERROR = 'LOAD_CHANGE_CALL_STATUS_ERROR';
export const BEGIN_LOAD_SUBMIT_MONEY = 'BEGIN_LOAD_SUBMIT_MONEY';
export const LOAD_SUBMIT_MONEY_SUCCESSFUL = 'LOAD_SUBMIT_MONEY_SUCCESSFUL';
export const LOAD_SUBMIT_MONEY_ERROR = 'LOAD_SUBMIT_MONEY_ERROR';
export const BEGIN_LOAD_STUDENT = 'BEGIN_LOAD_STUDENT';
export const LOAD_STUDENT_SUCCESSFUL = 'LOAD_STUDENT_SUCCESSFUL';
export const LOAD_STUDENT_ERROR = 'LOAD_STUDENT_ERROR';
export const BEGIN_UPLOAD_INFO_STUDENT_IMAGE =
  'BEGIN_UPLOAD_INFO_STUDENT_IMAGE';
export const UPLOADING_INFO_STUDENT_IMAGE_SUCCESSFUL =
  'UPLOADING_INFO_STUDENT_IMAGE_SUCCESSFUL';
export const UPLOADING_INFO_STUDENT_IMAGE_ERROR =
  'UPLOADING_INFO_STUDENT_IMAGE_ERROR';
export const BEGIN_UPDATING_STUDENT_PROFILE = 'BEGIN_UPDATING_STUDENT_PROFILE';
export const UPDATING_STUDENT_PROFILE_SUCCESSFUL =
  'UPDATING_STUDENT_PROFILE_SUCCESSFUL';
export const UPDATING_STUDENT_PROFILE_ERROR = 'UPDATING_STUDENT_PROFILE_ERROR';
export const BEGIN_LOAD_HISTORY_CALLS = 'BEGIN_LOAD_HISTORY_CALLS';
export const BEGIN_REFRESH_HISTORY_CALLS = 'BEGIN_REFRESH_HISTORY_CALLS';
export const LOAD_HISTORY_CALLS_SUCCESSFUL = 'LOAD_HISTORY_CALLS_SUCCESSFUL';
export const LOAD_HISTORY_CALLS_ERROR = 'LOAD_HISTORY_CALLS_ERROR';
export const BEGIN_LOAD_HISTORY_COLLECT = 'BEGIN_LOAD_HISTORY_COLLECT';
export const BEGIN_REFRESH_HISTORY_COLLECT = 'BEGIN_REFRESH_HISTORY_COLLECT';
export const LOAD_HISTORY_COLLECT_SUCCESSFUL =
  'LOAD_HISTORY_COLLECT_SUCCESSFUL';
export const LOAD_HISTORY_COLLECT_ERROR = 'LOAD_HISTORY_COLLECT_ERROR';
export const BEGIN_LOAD_INFO_STUDENT_PROGRESS =
  'BEGIN_LOAD_INFO_STUDENT_PROGRESS';
export const BEGIN_REFRESH_INFO_STUDENT_PROGRESS =
  'BEGIN_REFRESH_INFO_STUDENT_PROGRESS';
export const LOAD_INFO_STUDENT_PROGRESS_SUCCESSFUL =
  'LOAD_INFO_STUDENT_PROGRESS_SUCCESSFUL';
export const LOAD_INFO_STUDENT_PROGRESS_ERROR =
  'LOAD_INFO_STUDENT_PROGRESS_ERROR';
export const BEGIN_CHANGE_STUDENT_PASSWORD = 'BEGIN_CHANGE_STUDENT_PASSWORD';
export const CHANGE_STUDENT_PASSWORD_SUCCESSFUL =
  'CHANGE_STUDENT_PASSWORD_SUCCESSFUL';
export const CHANGE_STUDENT_PASSWORD_ERROR = 'CHANGE_STUDENT_PASSWORD_ERROR';

export const ON_SELECT_TASK_DATE = 'ON_SELECT_TASK_DATE';
export const BEGIN_LOAD_TASK_ANALYTICS = 'BEGIN_LOAD_TASK_ANALYTICS';
export const LOAD_TASK_ANALYTICS_SUCCESSFUL = 'LOAD_TASK_ANALYTICS_SUCCESSFUL';
export const LOAD_TASK_ANALYTICS_ERROR = 'LOAD_TASK_ANALYTICS_ERROR';
export const BEGIN_LOAD_TASK_VIEW = 'BEGIN_LOAD_TASK_VIEW';
export const LOAD_TASK_VIEW_SUCCESSFUL = 'LOAD_TASK_VIEW_SUCCESSFUL';
export const LOAD_TASK_VIEW_ERROR = 'LOAD_TASK_VIEW_ERROR';
export const BEGIN_LOAD_TASK_EMPLOYEES = 'BEGIN_LOAD_TASK_EMPLOYEES';
export const LOAD_TASK_EMPLOYEES_SUCCESSFUL = 'LOAD_TASK_EMPLOYEES_SUCCESSFUL';
export const LOAD_TASK_EMPLOYEES_ERROR = 'LOAD_TASK_EMPLOYEES_ERROR';

export const BEGIN_LOAD_NOTIFICATIONS = 'BEGIN_LOAD_NOTIFICATIONS';
export const LOAD_NOTIFICATIONS_SUCCESSFUL = 'LOAD_NOTIFICATIONS_SUCCESSFUL';
export const LOAD_NOTIFICATIONS_ERROR = 'LOAD_NOTIFICATIONS_ERROR';
export const BEGIN_LOAD_MORE_NOTIFICATIONS = 'BEGIN_LOAD_MORE_NOTIFICATIONS';
export const LOAD_MORE_NOTIFICATIONS_SUCCESSFUL =
  'LOAD_MORE_NOTIFICATIONS_SUCCESSFUL';
export const LOAD_MORE_NOTIFICATIONS_ERROR = 'LOAD_MORE_NOTIFICATIONS_ERROR';
export const BEGIN_REFRESH_NOTIFICATIONS = 'BEGIN_LOAD_MORE_NOTIFICATIONS';
export const REFRESH_NOTIFICATIONS_SUCCESSFUL =
  'REFRESH_NOTIFICATIONS_SUCCESSFUL';
export const REFRESH_NOTIFICATION_ERROR = 'REFRESH_NOTIFICATION_ERROR';
export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
export const BEGIN_READ_NOTIFICATIONS = 'BEGIN_READ_NOTIFICATIONS';
export const READ_NOTIFICATIONS_SUCCESSFUL = 'READ_NOTIFICATIONS_SUCCESSFUL';
export const READ_NOTIFICATIONS_ERROR = 'READ_NOTIFICATIONS_ERROR';

export const BEGIN_LOAD_PROFILE = 'BEGIN_LOAD_PROFILE';
export const LOAD_PROFILE_SUCCESSFUL = 'LOAD_PROFILE_SUCCESSFUL';
export const LOAD_PROFILE_ERROR = 'LOAD_PROFILE_ERROR';
export const BEGIN_CHANGE_AVATAR = 'BEGIN_CHANGE_AVATAR';
export const CHANGE_AVATAR_SUCCESSFUL = 'CHANGE_AVATAR_SUCCESSFUL';
export const CHANGE_AVATAR_ERROR = 'CHANGE_AVATAR_ERROR';
export const UPDATE_SYSTEM_AVATAR = 'UPDATE_SYSTEM_AVATAR';
export const BEGIN_UPDATE_PROFILE = 'BEGIN_UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESSFUL = 'UPDATE_PROFILE_SUCCESSFUL';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const BEGIN_LOAD_DOCUMENTS = 'BEGIN_LOAD_DOCUMENTS';
export const BEGIN_REFRESH_DOCUMENTS = 'BEGIN_REFRESH_DOCUMENTS';
export const LOAD_DOCUMENTS_SUCCESSFUL = 'LOAD_DOCUMENTS_SUCCESSFUL';
export const LOAD_DOCUMENTS_ERROR = 'LOAD_DOCUMENTS_ERROR';
export const BEGIN_LOAD_DEPARTMENT_FILTER = 'BEGIN_LOAD_DEPARTMENT_FILTER';
export const LOAD_DEPARTMENT_FILTER_SUCCESSFUL =
  'LOAD_DEPARTMENT_FILTER_SUCCESSFUL';
export const LOAD_DEPARTMENT_FILTER_ERROR = 'LOAD_DEPARTMENT_FILTER_ERROR';

export const BEGIN_LOAD_LEADS = 'BEGIN_LOAD_LEADS';
export const BEGIN_REFRESH_LEADS = 'BEGIN_REFRESH_LEADS';
export const LOAD_LEADS_SUCCESSFUL = 'LOAD_LEADS_SUCCESSFUL';
export const LOAD_LEADS_ERROR = 'LOAD_LEADS_ERROR';
export const BEGIN_SEARCH_LEADS = 'BEGIN_SEARCH_LEADS';
export const ON_SELECT_START_TIME_LEADS = 'ON_SELECT_START_TIME_LEADS';
export const ON_SELECT_END_TIME_LEADS = 'ON_SELECT_END_TIME_LEADS';
export const ON_SELECT_RATE_LEADS = 'ON_SELECT_RATE_LEADS';
export const ON_SELECT_CAMPAIGN_LEADS = 'ON_SELECT_CAMPAIGN_LEADS';
export const ON_SELECT_STATUS_LEADS = 'ON_SELECT_STATUS_LEADS';
export const ON_SELECT_SOURCE_LEADS = 'ON_SELECT_SOURCE_LEADS';
export const ON_SELECT_ADDRESS_LEADS = 'ON_SELECT_ADDRESS_LEADS';
export const ON_SELECT_PIC_LEADS = 'ON_SELECT_PIC_LEADS';
export const ON_SELECT_SORTED_BY_LEADS = 'ON_SELECT_SORTED_BY_LEADS';
export const RESET_FILTER_LEADS = 'RESET_FILTER_LEADS';
export const BEGIN_LOAD_LEAD_STAFFS = 'BEGIN_LOAD_STAFFS';
export const LOAD_LEAD_STAFFS_SUCCESSFUL = 'LOAD_STAFFS_SUCCESSFUL';
export const LOAD_LEAD_STAFFS_ERROR = 'LOAD_STAFFS_ERROR';
export const BEGIN_SAVE_LEAD = 'BEGIN_SAVE_LEAD';
export const SAVE_LEAD_SUCCESSFUL = 'SAVE_LEAD_SUCCESSFUL';
export const SAVE_LEAD_ERROR = 'SAVE_LEAD_ERROR';
export const BEGIN_CHANGE_CAMPAIGN_TAG = 'BEGIN_CHANGE_CAMPAIGN_TAG';
export const CHANGE_CAMPAIGN_TAG_SUCCESSFUL = 'CHANGE_CAMPAIGN_TAG_SUCCESSFUL';
export const CHANGE_CAMPAIGN_TAG_ERROR = 'CHANGE_CAMPAIGN_TAG_ERROR';
export const BEGIN_CHANGE_SOURCE_TAG = 'BEGIN_CHANGE_SOURCE_TAG';
export const CHANGE_SOURCE_TAG_SUCCESSFUL = 'CHANGE_SOURCE_TAG_SUCCESSFUL';
export const CHANGE_SOURCE_TAG_ERROR = 'CHANGE_SOURCE_TAG_ERROR';
export const BEGIN_CHANGE_STATUS_TAG = 'BEGIN_CHANGE_STATUS_TAG';
export const CHANGE_STATUS_TAG_SUCCESSFUL = 'CHANGE_STATUS_TAG_SUCCESSFUL';
export const CHANGE_STATUS_TAG_ERROR = 'CHANGE_STATUS_TAG_ERROR';
export const BEGIN_CHANGE_PIC_TAG = 'BEGIN_CHANGE_PIC_TAG';
export const CHANGE_PIC_TAG_SUCCESSFUL = 'CHANGE_PIC_TAG_SUCCESSFUL';
export const CHANGE_PIC_TAG_ERROR = 'CHANGE_PIC_TAG_ERROR';
export const ON_SELECT_CALL_BACK_START_TIME_LEADS = 'ON_SELECT_CALL_BACK_START_TIME_LEADS';
export const ON_SELECT_CALL_BACK_END_TIME_LEADS = 'ON_SELECT_CALL_BACK_END_TIME_LEADS';
export const ON_SELECT_MOCK_EXAM_START_TIME_LEADS = 'ON_SELECT_MOCK_EXAM_START_TIME_LEADS';
export const ON_SELECT_MOCK_EXAM_END_TIME_LEADS = 'ON_SELECT_MOCK_EXAM_END_TIME_LEADS';
export const ON_SELECT_DUPLICATE_LEADS = 'ON_SELECT_DUPLICATE_LEADS';
export const ON_SELECT_LEAD_TAG_LEADS = 'ON_SELECT_LEAD_TAG_LEADS';
export const ON_SELECT_BASE_ID_LEADS = 'ON_SELECT_BASE_ID_LEADS';
export const ON_SELECT_ORDER_BY_LEADS = 'ON_SELECT_ORDER_BY_LEADS';

export const BEGIN_LOAD_MANAGE_STAFF = 'BEGIN_LOAD_MANAGE_STAFF';
export const LOAD_MANAGE_STAFF_SUCCESSFUL = 'LOAD_MANAGE_STAFF_SUCCESSFUL';
export const LOAD_MANAGE_STAFF_ERROR = 'LOAD_MANAGE_STAFF_ERROR';
export const BEGIN_SEARCH_MANAGE_STAFF = 'BEGIN_SEARCH_MANAGE_STAFF';
export const BEGIN_REFRESH_MANAGE_STAFF = 'BEGIN_REFRESH_MANAGE_STAFF';
export const RESET_MANAGE_STAFF = 'RESET_MANAGE_STAFF';
export const BEGIN_LOAD_DEPARTMENTS = 'BEGIN_LOAD_DEPARTMENTS';
export const LOAD_DEPARTMENTS_SUCCESSFUL = 'LOAD_DEPARTMENTS_SUCCESSFUL';
export const LOAD_DEPARTMENTS_ERROR = 'LOAD_DEPARTMENTS_ERROR';
export const BEGIN_LOAD_ROLES = 'BEGIN_LOAD_ROLES';
export const LOAD_ROLES_SUCCESSFUL = 'LOAD_ROLES_SUCCESSFUL';
export const LOAD_ROLES_ERROR = 'LOAD_ROLES_ERROR';

export const BEGIN_LOAD_SHIFT_CLOCK = 'BEGIN_LOAD_SHIFT_CLOCK';
export const LOAD_SHIFT_CLOCK_SUCCESSFUL = 'LOAD_SHIFT_CLOCK_SUCCESSFUL';
export const LOAD_SHIFT_CLOCK_ERROR = 'LOAD_SHIFT_CLOCK_ERROR';
export const ON_SELECT_CLOCK_MANAGE_DATE = 'ON_SELECT_CLOCK_MANAGE_DATE';
export const BEGIN_LOAD_TEACHING_CLOCK = 'BEGIN_LOAD_TEACHING_CLOCK';
export const LOAD_TEACHING_CLOCK_SUCCESSFUL = 'LOAD_TEACHING_CLOCK_SUCCESSFUL';
export const LOAD_TEACHING_CLOCK_ERROR = 'LOAD_TEACHING_CLOCK_ERROR';
export const RESET_CLOCK = 'RESET_CLOCK';
export const BEGIN_LOAD_WORK_SHIFT_CLOCK = 'BEGIN_LOAD_WORK_SHIFT_CLOCK';
export const LOAD_WORK_SHIFT_CLOCK_SUCCESSFUL =
  'LOAD_WORK_SHIFT_CLOCK_SUCCESSFUL';
export const LOAD_WORK_SHIFT_CLOCK_ERROR = 'LOAD_WORK_SHIFT_CLOCK_ERROR';
export const ON_SELECT_WORK_SHIFT_CLOCK_EMPLOYEE =
  'ON_SELECT_WORK_SHIFT_CLOCK_EMPLOYEE';
export const LOAD_EMPLOYEE_WORK_SHIFT_CLOCK_SUCCESSFUL =
  'LOAD_EMPLOYEE_WORK_SHIFT_CLOCK_SUCCESSFUL';
export const ON_SELECT_EMPLOYEE_WORK_SHIFT_CLOCK_MANAGE_DATE =
  'ON_SELECT_EMPLOYEE_WORK_SHIFT_CLOCK_MANAGE_DATE';

export const BEGIN_LOAD_KPI = 'BEGIN_LOAD_KPI';
export const BEGIN_REFRESH_KPI = 'BEGIN_REFRESH_KPI';
export const LOAD_KPI_SUCCESSFUL = 'LOAD_KPI_SUCCESSFUL';
export const LOAD_KPI_ERROR = 'LOAD_KPI_ERROR';
export const BEGIN_SEARCH_KPI = 'BEGIN_SEARCH_KPI';
export const RESET_KPI = 'RESET_KPI';
export const SELECTED_KPI_TYPE = 'SELECTED_KPI_TYPE';
export const SELECTED_KPI_CALCULATE_BY = 'SELECTED_KPI_CALCULATE_BY';
export const SELECTED_KPI_START_TIME = 'SELECTED_KPI_START_TIME';
export const SELECTED_KPI_END_TIME = 'SELECTED_KPI_END_TIME';
export const BEGIN_LOAD_KPI_SETTINGS = 'BEGIN_LOAD_KPI_SETTINGS';
export const LOAD_KPI_SETTINGS_SUCCESS = 'LOAD_KPI_SETTINGS_SUCCESS';
export const LOAD_KPI_SETTINGS_ERROR = 'LOAD_KPI_SETTINGS_ERROR';
export const BEGIN_LOAD_KPI_EMPLOYEES = 'BEGIN_LOAD_KPI_EMPLOYEES';
export const LOAD_KPI_EMPLOYEES_SUCCESS = 'LOAD_KPI_EMPLOYEES_SUCCESS';
export const LOAD_KPI_EMPLOYEES_ERROR = 'LOAD_KPI_EMPLOYEES_ERROR';
export const BEGIN_ADD_KPIS = 'BEGIN_ADD_KPIS';
export const ADD_KPIS_SUCCESS = 'ADD_KPIS_SUCCESS';
export const ADD_KPIS_ERROR = 'ADD_KPIS_ERROR';
export const BEGIN_LOAD_KPI_CAMPAIGNS = 'BEGIN_LOAD_KPI_CAMPAIGNS';
export const LOAD_KPI_CAMPAIGNS_SUCCESS = 'LOAD_KPI_CAMPAIGNS_SUCCESS';
export const LOAD_KPI_CAMPAIGNS_ERROR = 'LOAD_KPI_CAMPAIGNS_ERROR';
export const BEGIN_LOAD_KPI_SOURCES = 'BEGIN_LOAD_KPI_SOURCES';
export const LOAD_KPI_SOURCES_SUCCESS = 'LOAD_KPI_SOURCES_SUCCESS';
export const LOAD_KPI_SOURCES_ERROR = 'LOAD_KPI_SOURCES_ERROR';
export const BEGIN_LOAD_KPI_COURSES = 'BEGIN_LOAD_KPI_COURSES';
export const LOAD_KPI_COURSES_SUCCESS = 'LOAD_KPI_COURSES_SUCCESS';
export const LOAD_KPI_COURSES_ERROR = 'LOAD_KPI_COURSES_ERROR';

export const BEGIN_LOAD_TABS = 'BEGIN_LOAD_TABS';
export const LOAD_TABS_SUCCESSFUL = 'LOAD_TABS_SUCCESSFUL';
export const LOAD_TABS_ERROR = 'LOAD_TABS_ERROR';

export const BEGIN_LOAD_SCHEDULES = 'BEGIN_LOAD_SCHEDULES';
export const LOAD_SCHEDULES_SUCCESS = 'LOAD_SCHEDULES_SUCCESS';
export const LOAD_SCHEDULES_ERROR = 'LOAD_SCHEDULES_ERROR';
export const ON_SELECT_START_DATE_SCHEDULES = 'ON_SELECT_START_DATE_SCHEDULES';
export const ON_SELECT_END_DATE_SCHEDULES = 'ON_SELECT_END_DATE_SCHEDULES';
export const ON_SELECT_PROVINCE_SCHEDULES = 'ON_SELECT_PROVINCE_SCHEDULES';
export const ON_SELECT_BASE_SCHEDULES = 'ON_SELECT_BASE_SCHEDULES';
export const ON_SELECT_COURSE_SCHEDULES = 'ON_SELECT_COURSE_SCHEDULES';
export const ON_SELECT_TYPE_SCHEDULES = 'ON_SELECT_TYPE_SCHEDULES';
export const ON_SELECT_TEACHER_SCHEDULES = 'ON_SELECT_TEACHER_SCHEDULES';

export const BEGIN_LOAD_FORMS = 'BEGIN_LOAD_FORMS';
export const LOAD_FORMS_SUCCESS = 'LOAD_FORMS_SUCCESS';
export const LOAD_FORMS_ERROR = 'LOAD_FORMS_ERROR';
export const BEGIN_REFRESH_FORMS = 'BEGIN_REFRESH_FORMS';
export const BEGIN_SEARCH_FORMS = 'BEGIN_SEARCH_FORMS';
export const RESET_FORMS = 'RESET_FORMS';
export const BEGIN_CREATE_FORM = 'BEGIN_CREATE_FORM';
export const CREATE_FORM_SUCCESS = 'CREATE_FORM_SUCCESS';
export const CREATE_FORM_ERROR = 'CREATE_FORM_ERROR';
export const BEGIN_UPDATE_FORM = 'BEGIN_UPDATE_FORM';
export const UPDATE_FORM_SUCCESS = 'UPDATE_FORM_SUCCESS';
export const UPDATE_FORM_COMPLETE = 'UPDATE_FORM_COMPLETE';
export const BEGIN_DUPLICATE_FORM = 'BEGIN_DUPLICATE_FORM';
export const DUPLICATE_FORM_SUCCESS = 'DUPLICATE_FORM_SUCCESS';
export const DUPLICATE_FORM_COMPLETE = 'DUPLICATE_FORM_COMPLETE';
export const BEGIN_DELETE_FORM = 'BEGIN_DELETE_FORM';
export const DELETE_FORM_SUCCESS = 'DELETE_FORM_SUCCESS';
export const DELETE_FORM_COMPLETE = 'DELETE_FORM_COMPLETE';
