# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'ColorMEManager' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ColorMEManager
  pod 'RNMobileCenter', '~> 0.4.0'
  pod 'MobileCenter', '~> 0.6.0'

  

  target 'ColorMEManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ColorMEManager-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ColorMEManager-tvOS

  target 'ColorMEManager-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
