# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ColorMEManager' do
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.1'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ColorMEManager
  
  platform :ios, '9.0'
  target 'ColorMEManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ColorMEManager-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ColorMEManager-tvOS

  target 'ColorMEManager-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
