require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'
platform :ios, '10.0'

target 'ColorMEManager' do

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'
  pod 'OpenSSL-Universal', '~>1.0.2.20'

  target 'ColorMEManagerTests' do
    inherit! :complete
    # Pods for testing
  end

    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable these next few lines.
    use_flipper!
    post_install do |installer|
      flipper_post_install(installer)
    end
end
